jwt:
  header: Authorization
  secret: my-very-secret-key
logging:
  level:
    root: ERROR
    org:
      springframework: DEBUG

server:
  port: 8081

social:
  twitter:
    consumerKey: UvhExjFNaoxEGMq22MinBa5mc
    consumerSecret: 2Wb0PncZQy4uyGAOnG3aRQ0hUpaELhYbSiBUbtKDRyoMZvhfft
    accessToken: 880588741-TAXbr0TQSs1r8uLEeaKsMa7HfHQc0nARfzEypsRp
    accessTokenSecret: 25t5gs6YKYlVl1yeXyxLufGdqbLbSwUjJNsWZshoXcUnJ

taskExecutor:
  enabled: false
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100

spring:
  data:
    neo4j:
      username: neo4j
      password: neo5j